### ISSUE TITLE
 chain_dangle.json rotation issue

### ISSUE THREAD

**Issue by Nazenn** [the-realest-stu/Rustic#11]
Right now chain_dangle.json will rotate depending on the orientation of the horizontal chain, while the normal vertical chain mesh does not. This makes supporting this mod with 3d chain meshes, or more detailed textures that require the chain lines to line up near impossible as the chain will always be out of alignment with one set of chain directions. 

Image of the issue as it stands now: https://www.dropbox.com/s/cur9162wamcjmqc/2017-05-22_15.32.07.png?dl=0
Sorry for the image being a bit messy, this is my texturing world for this mod and I was in the middle of setting it up for the new update when I found the issue

**Comment by the-realest-stu** [comment]
I thought resource packs allowed you to provide custom blockstate files? If that is the case, you could just make a new blockstate file for chain, and remove the default model, and instead make the default model into a submodel based on the axis, and just rotate the submodel instead of the whole block. I'd rather not change the current blockstate file to something like that, because that's how I had things initially, but it caused problems (the dangle model was having z-fighting issues with the chain model, so I shortened one plane in the dangle model by one pixel, and made it rotate with the rest of the model so it would allign properly. not sure if that makes sense). Depending on how you do things, you shouldn't run into those problems, though, if you do something like that.

**Comment by the-realest-stu** [comment]
Upon further research, it seems as though you can, in fact, provide custom blockstate jsons.
I wrote a blockstate json with the changes I described before:
`{
    "forge_marker": 1,
    "defaults": {},
    "variants": {
        "axis": {
            "y": { "submodel": { "chain": { "model": "rustic:chain" } } },
            "z": { "submodel": { "chain": { "model": "rustic:chain_horizontal" } } },
            "x": { "submodel": { "chain": { "model": "rustic:chain_horizontal", "y": 90 } } }
        },
        "dangle": {
            "true": { "submodel": { "dangle": { "model": "rustic:chain_dangle" } } },
            "false": {}
        },
	"inventory": []
    }
}`
