### ISSUE TITLE
Olive oiled foods not returning empty bottles upon craft

### ISSUE THREAD

**Issue by Febilian** [the-realest-stu/Rustic#12]
Unsure if intended as I'd never tried it before. I'm loving the update's contents so far, but it seems a tad silly to consume the entire bottle as well when rubbing olive oil on food. Heh.

When I tried just crafting one at a time, the bottle at first appeared in the crafting input where the olive oil bottle was, but trying to take it out resulted in it disappearing. Shift-clicking multiple outputs out at once doesn't leave any bottles at all, even visually.

EDIT: Forgot to mention I'm using 0.3.1

**Comment by the-realest-stu** [comment]
That's a known issue. Basically, when you craft with a tool or bucket that isnt consumed, the stack is replaced in the crafting grid with a new stack of the damaged item or empty bucket. That doesn't work for olive oil bottles, though, because they are stackable, so I can't replace the itemstack without deleting the remaining olive oil bottles. What I'll probably do is add an event that detects when you craft with a fluid bottle and then make that give the crafter an empty bottle

**Comment by the-realest-stu** [comment]
Done. The fix will be included in the next version of Rustic, which should be released in the next few days.
