### ISSUE TITLE
Request: Grape vines spread and latice 

### ISSUE THREAD

**Issue by iobiarg** [the-realest-stu/Rustic#138]
Hi. I've been using your mod and i really love it..
But  I think it would be more real to be able to spread the grape vines a couple more blocks since in real life a plant cant spread like 3 meters by 3 meters... 

Then, it would be pretty useful in terms of aesthetic, to be able to tie rope to the lattice things since they fit better the lanterns/lamps.

Then... the chilly pepper and the tomatoes "graphic" in the pant are pretty basic and undetailed compared to what you did with apples and grapes and berries... a new skin o model would be nice, along with some more complex use of the item...

Finally, there should be a way to take of the "example" brew you put in the brewer without having to break it. I mean, if i brew an ale of 0.65 and i want ot use as base the one i get with 0.69 i could just put the previous in a bottle or just overlap with the new one. It would also be nice to be able to charge the brewer with the barrel without accessing the GUI. 

Your mod is awesome... i hope you keep developing it and making more stuff...

PD: Sorry for my bad English... I can help you with Spanish and Portuguese translation if you want or need.

**Comment by Lethann** [comment]
I agree that the grapes should spread a bit more. Maybe 2 on each side rather than 1?

**Comment by the-realest-stu** [comment]
I agree that grapes should spread a bit more, although I'm not sure I'll end up implementing that in Rustic 1 because I'd have to rewrite how grapes spread.

I can make rope connect to lattice in the next update of the mod.

Chile peppers and tomatoes have a lot of issues, including the graphics. I think that's another problem that will be solved in Rustic 2 instead of 1.

You should be able to remove the starter brew from the barrel by putting an empty bottle in the input slot of the starter brew tank, just like the output tank. I can test that to make sure it works before I release the next update.

Thanks for the suggestions and reports! Oh, and if you want to translate the mod, feel free to make a pull request.

**Comment by the-realest-stu** [comment]
I just made rope connect to lattice. I plan on releasing an update with this tweak and some bug fixes within a day or two.
