### ISSUE TITLE
Culture Booze Bug

### ISSUE THREAD

**Issue by Ryanman7** [the-realest-stu/Rustic#144]
I've acquired a culture booze of 0.75 quality and added it to the brewing barrel, yet every time I brew, the resulting booze is of 0.25 quality. Am I doing something wrong here? How can I increase the quality of my booze?

**Comment by twilytgardnfaery** [comment]
Having the same problem since updating to version 1.4 of Revelation.  Prior to upgrade, I had managed to increase the quality of my Mead and Wildberry Wine to 1.0, but was still working on the iron wine, cider, and wine (from grape juice).  Since the update, my 0.70 Cider has been consistently producing 0.29 Cider, 0.67 Iron Wine yields 0.17 Iron Wine, and 0.94 Wine produces 0.44 Wine.

**Comment by the-realest-stu** [comment]
You need to go into the Rustic's config file and delete anything related to brewing. The game will automatically regenerate those parts but with the correct values.
