### ISSUE TITLE
[Request] Configuration option to disable Alchemy feature

### ISSUE THREAD

**Issue by NotAVerb** [the-realest-stu/Rustic#148]
I'd like the alchemy specific parts of the mod to be treated as a module that can be enabled and disabled.

**Comment by NotAVerb** [comment]
Another option to disable the ability to stack up to sixteen elixirs would also be much appreciated.

**Comment by the-realest-stu** [comment]
The ability to stack up to 16 is the entire point of elixirs, so I won't be adding any config options for that, sorry. As for disabling all features related to alchemy, that would be less than trivial to implement, and I'm not focusing development on this mod anymore, so I won't be adding a option for that either. Maybe in Rustic 2, although I can't guarantee it due to some plans I have for alchemy in Rustic 2.

**Comment by NotAVerb** [comment]
Would it be easier to disable the world generation of the herbs? The herbs are what keep me from just removing the recipes for the condenser blocks with crafttweaker.

**Comment by the-realest-stu** [comment]
You can already disable herb generation. Just set the herb generation chance to zero in the config file.
