### ISSUE TITLE
1.11.2 Client crash with NEI

### ISSUE THREAD

**Issue by Renadarain** [the-realest-stu/Rustic#15]
Hi,

Rustic 0.3 and 0.31 crashes the client on server join with the following crash report.  0.2 is fine.

https://pastebin.com/aQHv8RXV

Regards,
Renada

**Comment by the-realest-stu** [comment]
Hmmm... That's odd. Based solely in the log, it looks like a problem with NEI, but if it works fine without the latest versions of Rustic, then it must be on me. The stacktrace never seems to mention any of my classes, though, so this should be interesting to fix.

**Comment by Renadarain** [comment]
lol I wish you luck :)

**Comment by the-realest-stu** [comment]
I've looked into this some more, and I really just can't find any way that this could be a problem with in Rustic. Report this to whoever is maintaining NEI right now, too, it should at least be easier for them to figure out whats going on.

**Comment by the-realest-stu** [comment]
Okay, that's odd. It works perfectly fine now, at least in my dev environment. I think the issue was the same as the one in #16, so fixing that also fixed this. The fix, assuming it works outside of my dev environment, will be included in the next version of Rustic, which will be releases today or tommorow (or maybe the day after that).

**Comment by Renadarain** [comment]
Cool beans, thank you :)

**Comment by Renadarain** [comment]
Ok will do, thanks for checking :)

**Comment by Renadarain** [comment]
All fixed, thank you :)
