### ISSUE TITLE
[Wiki|Request] Providing Crafttweaker examples

### ISSUE THREAD

**Issue by chaos234** [the-realest-stu/Rustic#150]
Like the titel states I miss a few examples for each possible Crafttweaker methode.

Would be niche, if you could give a foew to each of the "adds" methode :)

**Comment by the-realest-stu** [comment]
Done. The crafttweaker wiki should also be helpful. It won't explain the Rustic compat, but understanding the basics will be helpful regardless.

**Comment by NotAVerb** [comment]
So is it not possible to have the second input of the normal condenser be nothing then?
This line returns errors and adding brackets around null only creates a valid recipe for the advanced condenser. Angle brackets around null also give errors.
`mods.rustic.Condenser.addRecipe(<rockhounding_surface:aging_items>, <rockhounding_surface:gypsum_items:4>, null);`

The ItemStack page of the CraftTweaker wiki doesn't mention anything about `null` which leads me to believe I can't do what I'm trying to do. If It's possible to create normal condenser recipes with a single ingredient I'd appreciate another example because this has me stuck.
