### ISSUE TITLE
Recipe Guide

### ISSUE THREAD

**Issue by torinberger** [the-realest-stu/Rustic#192]
Hello, I love the mod (probably my favourite mods so far), keep up the good work. Anyway I have had a look and cant seem to find any documentation for the crafting recipes (at-least not for all things). I'm currently at an airport but when I get back I might compile all the recipes from the JSON files, to something a bit more user friendly. Anyway, lemme know if the docs are somewhere in a dark cave.

**Comment by the-realest-stu** [comment]
I never documented the recipes since I just assumed that anyone using the mod would also be using JEI. If you do not have JEI installed, I highly recommend installing it since it can be used to see the recipe of just about anything, and it even works for recipes that don't use a crafting table (like crushing recipes and alchemy recipes from Rustic).
