### ISSUE TITLE
Crash w/ the Cabinet

### ISSUE THREAD

**Issue by WenXin20** [the-realest-stu/Rustic#31]
Forge 1.10.2-2281
Rustic v0.1.2.2
I got this crash after I died. I also noticed that my game freezes if I try to break the cabinet.
[Crash Report](https://pastebin.com/s8fUhaKK)

**Comment by the-realest-stu** [comment]
Sadly, I can't really fix bugs in the 1.10 version, as I already messed about with the code in a backporting attempt, and in order to do anything with that version, I'd have to finish the backport, whic would take quite  a while. I'd suggest you use forge's config and enable the option that deletes erroring tileentities.

Sorry.

**Comment by WenXin20** [comment]
Ok, thats fine. Thanks for the help.
