### ISSUE TITLE
Items Registered in Wrong event.

### ISSUE THREAD

**Issue by BloodWorkXGaming** [the-realest-stu/Rustic#52]
The Items are not getting registered in the new Registry Event in 1.12.

This causes issues for other mods, like crafttweaker, as it is registering it's recipes in the recipe event which is before your items exist.

Moving [these few lines](https://github.com/the-realest-stu/Rustic/blob/master/src/main/java/rustic/core/CommonProxy.java#L48) to the new event should fix it.

**Comment by the-realest-stu** [comment]
According to forge, the registry events are fired after preInit, so registering things in preinit should cause things to be registered before anything else happens. I know I'm doing things "wrong", and I do plan on redoing all of that stuff eventually, but it's not a priority unless someone shows me an actual problem caused by me registering things stupidly.

**Comment by BloodWorkXGaming** [comment]
Ye, no worries, should have deleted this issue again, we found out it was a bug on CT side that the recipes  were loaded too early.
