### ISSUE TITLE
Some of Rustic's herbs don't register properly for harvesting.

### ISSUE THREAD

**Issue by Serifina** [the-realest-stu/Rustic#78]
Reference [this issue](https://github.com/TehNut/Harvest/issues/7#issuecomment-326660836). 

MC 1.12.1
Forge 14.22.0.2.2467
SimpleHarvest 1.12-1.2.4-16
Rustic 0.4.1

Trying to register Rustic's herbs in order to have right-click harvesting on them work, and while four of them do, the other eight do not. TehNut says they don't appear to implement IPlantable properly, which is why it fails. Is it possible to fix this? The eight that do not work are Horsetail, Deathstalk Mushroom, Cohosh, Chamomile, Blood Orchid, Aloe Vera, Mooncap Mushroom, and Wind Thistle.

**Comment by the-realest-stu** [comment]
I'd have to look into how IPlantable actually works. Definitely possible, and I'll look into it, but it isn't necessarily a priority.

**Comment by TehNut** [comment]
I tried getting your attention on Discord, but the issue seems more like items for the crops that don't work just aren't being registered properly. 

The [four here](https://github.com/the-realest-stu/Rustic/blob/master/src/main/java/rustic/common/blocks/crops/Herbs.java#L38-L41) that have specific items work fine, according to OP, however the rest do not. I believe that is because [when you register them](https://github.com/the-realest-stu/Rustic/blob/master/src/main/java/rustic/common/blocks/crops/Herbs.java#L44), you are passing `false` for `hasItemBlock` which causes the block to [register a default `ItemBlock` instance](https://github.com/the-realest-stu/Rustic/blob/master/src/main/java/rustic/common/blocks/crops/BlockHerbBase.java#L49-L51). This default `ItemBlock` does not implement `IPlantable` which causes Harvest to not pick up on it.

`IPlantable` is the crop interface for the seed item and should not be implemented on blocks. `IGrowable` is the block end of it. Honestly, the `IPlantable`/`IGrowable` system is utter garbage and needs to be rewritten, but sadly all previous attempts have been shot down or died off.

**Comment by the-realest-stu** [comment]
Fixed this and released an update. It should work fine now. Thanks, TehNut, for the explanation of IPlantable and IGrowable.
