### ISSUE TITLE
Bees/honey spawn incredibly fast in apiary

### ISSUE THREAD

**Issue by viveleroi** [the-realest-stu/Rustic#80]
This seems unintentional, but when I place a bee in an apiary, within 20 minutes or less I have 64 bees and 64 honey.

Forge 1.12.1, rustic 0.4.1

**Comment by the-realest-stu** [comment]
It's actually intentional, since when I first added bees, honeycomb could only be used for candle-making, and I felt that it shouldn't take too long to get it if it's only use was for decorative items. I guess that doesn't apply so much anymore, now that mead is a thing, and honeycomb can be used in alchemy. I've halved the production and reproduction rates of bees for the next release (should come out within a day), but those rates have always been configurable, so if it's still too fast, you can slow it down through the config file. Halving the default rates is just a temporary fix, though, as I still plan on redesigning bees from the ground up in a future release.

**Comment by the-realest-stu** [comment]
Just released the update with the slower default speeds. Use the config options if necessary.
