### ISSUE TITLE
Dynamic trees support?

### ISSUE THREAD

**Issue by Sunconure11** [the-realest-stu/Rustic#83]
https://minecraft.curseforge.com/projects/dynamictrees

An API of sorts is being planned for this mod. When the time comes, would it be possible to add support for it?

**Comment by the-realest-stu** [comment]
Maybe? I guess it depends on if other mods end up adopting it or not. It seems like a cool mod, but I wouldn't use it unless the trees from mods like BOP were also made compatible. It would be hard to find the motivation to add support for something like that if it wasn't super popular or I wasn't going to use it myself, because I'd imagine that even with an API, adding support for that mod wouldn't be super easy.

**Comment by Deshiba** [comment]
With the API it would be possible for others to add the compatibility by making a bridging mod (add-on). This does require trees from your mod to be disabled trough configuration though. I suppose this is possible trough setting all the world generation options for trees to 0?

**Comment by the-realest-stu** [comment]
I just implemented this, and it will be released whenever Dynamic Trees updates (which should be tonight, if all goes according to plan).
