### ISSUE TITLE
[1.12 Suggestion] Ceramics Bucket Support on the Drying Basin 

### ISSUE THREAD

**Issue by MasterEnderman** [the-realest-stu/Rustic#92]
I tried using a clay bucket from Ceramics on the Drying Basin, but it wouldn't put the liquid in. A normal iron bucket works fine. Could you add support for buckets from other mods as well?

**Comment by sdaddy** [comment]
It seems all the liquid containers in Rustic are hard-coded to only use the vanilla bucket. Correct me if I'm wrong. I've tried using buckets from 3+ different mods and none of them work.

I'm working on a no/low-tech skyblock pack and created a recipe for crushing water into leaves with the Crushing Tub. However, it's become very difficult trying to get the water out since there's no access to iron at this stage of the pack.

Love the mod, would love it more if this was fixed. :)

**Comment by crysthala** [comment]
I'd love this functionality, too. Ceramics goes well thematically with Rustic, and it's probably being used in quite a few low-tech modpacks. Compatibility would be much appreciated!

**Comment by the-realest-stu** [comment]
I just released an update on curseforge which adds compatibility. Turns out I hadn't actually hardcoded anything to only work with vanilla buckets, I just needed to take a few more possibilities into account in the code that decided if something was a bucket or not.
