### ISSUE TITLE
cross mod compatibility 

### ISSUE THREAD

**Issue by Sayonarakansas** [the-realest-stu/Rustic#93]
so do you think that it would be possible for pams harvest craft olives to be used in the crusher? it gets pretty frustrating having to types of olives that aren't interchangeable. the same could be said about grapes.  and maybe adding support. 
another suggestion is adding grog. grog gives a diluted effect of any other alcoholic beverages available and if tough as nails is installed it creates a mechanic where you can mass produce a clean drinking liquid.
also your olive oil doesn't seem to work with cooking with blockheads crafting mechanics but that might be an issue on their side.
also maybe add hot beverages that will warm up the TAN temperature meter.

**Comment by the-realest-stu** [comment]
Harvestcraft support isn't planned. Grog is a cool idea, but I wouldn't be comfortable messing with TAN's balance that much. Other TAN support has already been suggested in #19.

Closing the issue, since the only suggestion from the list that I plan on implementing is already listed in another issue.
